function[] = letter_recognition()

%Okno programu
window.handle = figure('units', 'pixels', ...
                'position', [500 300 400 400], ...
                'menubar', 'none', ...
                'name', 'Automat Deterministyczny', ...
                'color', 'white', ...
                'numbertitle', 'off', ...
                'resize', 'off');

%Tytu³
S.tx = uicontrol('style', 'tex', ...
                'position', [0 370 400 20],...
                'backgroundcolor', get(window.handle, 'color'), ...
                'fontsize', 12, 'fontweight', 'bold', ... 
                'string', 'parametry automatu');

%Labelki
uicontrol('style', 'tex', ...
          'position', [20 320 100 20], ...
          'backgroundcolor', get(window.handle, 'color'), ...
          'fontsize', 12, 'fontweight', 'bold', ... 
          'string', 'liczba cech: ');
uicontrol('style', 'tex', ...
          'position', [20 280 160 20], ...
          'backgroundcolor', get(window.handle, 'color'), ...
          'fontsize', 12, 'fontweight','bold', ... 
          'string', 'liczba klas symboli: ');
uicontrol('style', 'tex', ...
          'position', [20 240 100 20], ...
          'backgroundcolor', get(window.handle, 'color'), ...
          'fontsize', 12, 'fontweight', 'bold', ... 
          'string', 'liczba kopii: ');
uicontrol('style', 'tex', ...
          'position', [20 200 170 20], ...
          'backgroundcolor', get(window.handle, 'color'), ...
          'fontsize', 12, 'fontweight', 'bold', ... 
          'string', 'wartoœæ maksymalna: ');
uicontrol('style', 'tex', ...
          'position', [20 160 110 20], ...
          'backgroundcolor', get(window.handle, 'color'), ...
          'fontsize', 12, 'fontweight', 'bold', ... 
          'string', 'liczba iteracji: ');
uicontrol('style', 'tex', ...
          'position', [20 120 100 20], ...
          'backgroundcolor', get(window.handle, 'color'), ...
          'fontsize', 12, 'fontweight', 'bold', ... 
          'string', 'liczba rojów: ');
            
%Edit texty
window.cechy = uicontrol('style', 'edit', ...
                         'unit', 'pix', ...
                         'position', [130 320 100 25], ...
                         'string', '5', ...
                         'callback', @check_number);
window.symbole = uicontrol('style', 'edit', ...
                         'position', [190 280 100 25], ...
                         'string', '10', ...
                         'callback', @check_number);
window.kopie = uicontrol('style', 'edit', ...
                         'position', [130 240 100 25], ...
                         'string', '100', ...
                         'callback', @check_number);
window.max = uicontrol('style', 'edit', ...
                         'position', [200 200 100 25], ...
                         'string', '20', ...
                         'callback', @check_number);
window.iteracje = uicontrol('style', 'edit', ...
                         'position', [140 160 100 25], ...
                         'string', '100', ...
                         'callback', @check_number);
window.roje = uicontrol('style', 'edit', ...
                         'position', [130 120 100 25], ...
                         'string', '30', ...
                         'callback', @check_number);
             
%Przycisk
window.computeButton = uicontrol('style', 'push', ...
                'units', 'pix', ...
                'position', [145 30 100 50], ...
                'fontsize', 14, ...
                'string', 'Compute', ...
                'callback', {@test_script,...
                             str2double(get(window.cechy, 'string')), ...
                             str2double(get(window.symbole, 'string')), ...
                             str2double(get(window.kopie, 'string')), ...
                             str2double(get(window.max, 'string')), ...
                             str2double(get(window.iteracje, 'string')), ...
                             str2double(get(window.roje, 'string'))});
end