function[] = rozpoznawanie_liter()
%Okno programu
handles.figure = figure('units', 'pixels', ...
                'position', [500 100 400 520], ...
                'menubar', 'none', ...
                'name', 'Automat Deterministyczny', ...
                'color', 'white', ...
                'numbertitle', 'off', ...
                'resize', 'off');

%Tytu³
uicontrol('style', 'tex', ...
          'position', [0 490 400 20],...
          'backgroundcolor', get(handles.figure, 'color'), ...
          'fontsize', 12, 'fontweight', 'bold', ... 
          'string', 'Parametry automatu:');

%Labelki
uicontrol('style', 'tex', ...
          'position', [20 440 220 20], ...
          'backgroundcolor', get(handles.figure, 'color'), ...
          'fontsize', 12, 'fontweight', 'bold', ... 
          'string', 'ograniczenie dla niedeterm: ');   
uicontrol('style', 'tex', ...
          'position', [20 400 170 20], ...
          'backgroundcolor', get(handles.figure, 'color'), ...
          'fontsize', 12, 'fontweight', 'bold', ... 
          'string', 'wartoœæ maksymalna: ');
uicontrol('style', 'tex', ...
          'position', [20 360 235 20], ...
          'backgroundcolor', get(handles.figure, 'color'), ...
          'fontsize', 12, 'fontweight', 'bold', ... 
          'string', 'œrednia rozk³adu normalnego: ');   
uicontrol('style', 'tex', ...
          'position', [20 320 250 20], ...  
          'backgroundcolor', get(handles.figure, 'color'), ...
          'fontsize', 12, 'fontweight', 'bold', ... 
          'string', 'wariancja rozk³adu normalnego: '); 
uicontrol('style', 'tex', ...
          'position', [20 280 100 20], ...
          'backgroundcolor', get(handles.figure, 'color'), ...
          'fontsize', 12, 'fontweight', 'bold', ... 
          'string', 'liczba kopii: ');
uicontrol('style', 'tex', ...
          'position', [20 240 100 20], ...
          'backgroundcolor', get(handles.figure, 'color'), ...
          'fontsize', 12, 'fontweight', 'bold', ... 
          'string', 'liczba cech: ');
uicontrol('style', 'tex', ...
          'position', [20 200 160 20], ...
          'backgroundcolor', get(handles.figure, 'color'), ...
          'fontsize', 12, 'fontweight','bold', ... 
          'string', 'liczba klas symboli: ');
uicontrol('style', 'tex', ...
          'position', [20 160 110 20], ...
          'backgroundcolor', get(handles.figure, 'color'), ...
          'fontsize', 12, 'fontweight', 'bold', ... 
          'string', 'liczba iteracji: ');
uicontrol('style', 'tex', ...
          'position', [20 120 100 20], ...
          'backgroundcolor', get(handles.figure, 'color'), ...
          'fontsize', 12, 'fontweight', 'bold', ... 
          'string', 'liczba rojów: ');
uicontrol('style', 'tex', ...
          'position', [20 80 200 20], ...
          'backgroundcolor', get(handles.figure, 'color'), ...
          'fontsize', 12, 'fontweight', 'bold', ... 
          'string', 'liczba symboli do testów: ');
         
%Edit texty
handles.ograniczenie = uicontrol('style', 'edit', ...
                         'position', [250 440 100 25], ...
                         'string', '4', ...
                         'callback', {@czy_liczba}); 
handles.max = uicontrol('style', 'edit', ...
                         'position', [200 400 100 25], ...
                         'string', '20', ...
                         'callback', {@czy_liczba});
handles.srednia = uicontrol('style', 'edit', ...
                         'position', [265 360 100 25], ...
                         'string', '0', ...
                         'callback', {@czy_liczba});
handles.wariancja = uicontrol('style', 'edit', ...
                         'position', [280 320 100 25], ...
                         'string', '3', ...
                         'callback', {@czy_liczba});
handles.kopie = uicontrol('style', 'edit', ...
                         'position', [130 280 100 25], ...
                         'string', '100', ...
                         'callback', {@czy_liczba});
handles.cechy = uicontrol('style', 'edit', ...
                         'unit', 'pix', ...
                         'position', [130 240 100 25], ...
                         'string', '5', ...
                         'callback', {@czy_liczba});
handles.symbole = uicontrol('style', 'edit', ...
                         'position', [190 200 100 25], ...
                         'string', '10', ...
                         'callback', {@czy_liczba});
handles.iteracje = uicontrol('style', 'edit', ...
                         'position', [140 160 100 25], ...
                         'string', '100', ...
                         'callback', {@czy_liczba});
handles.roje = uicontrol('style', 'edit', ...
                         'position', [130 120 100 25], ...
                         'string', '30', ...
                         'callback', {@czy_liczba});
handles.symbole_testowe = uicontrol('style', 'edit', ...
                         'position', [230 80 100 25], ...
                         'string', '10', ...
                         'callback', {@czy_liczba});                    
             
%Przycisk
handles.computeButton = uicontrol('style', 'push', ...
                'units', 'pix', ...
                'position', [145 10 100 50], ...
                'fontsize', 14, ...
                'string', 'Symuluj', ...
                'callback', @test_skrypt);

guidata(handles.figure, handles);
             
end
